### ISSUE TITLE
Add the ability to detect if a menu has a selected item in it

### ISSUE THREAD

**Issue by nickdenardis** [waynestate/parse-menu#1]
If there is a page_id passed in to the config and the menu is parsed there is no way to tell after the fact _if_ a menu item has actually been found.

**Comment by nickdenardis** [comment]
This could be done with one of two interfaces:

**1. Doing the detection on the 'app' by returning `$this->path` which is an array of the selected menu items from the root to the leaf.**

``` php
/**
 * @return array
 */
public function getPath();
```

_Pros:_
- No overhead in the class
- Exposes information that is already known.

_Cons_
- `$this->path` is based on the last `->parse(..)` so if there are multiple passes the data is only accurate after each pass
- Puts the logic on the app to figure out a `parse-menu` internals

**2. Doing the detection in the class itself and returning the result**

``` php
/**
 * @return boolean
 */
public function hasSelected(array &$menu);
```

_Pros:_
- Clean API for the app
- Doesn't expose `parse-menu` internals

_Cons:_
- Must pass in an array of the parsed menu since the class is stateless

Do either of you have a preference? @chrispelzer @robertvrabel

**Comment by robertvrabel** [comment]
I think doing the logic in the class is better. But since parse is already looping through everything, couldn't it set a private var (boolean) within the class if it found itself in the class or not when its all done? Then on the app side you could reference $parseMenu->isSelected() after. Something like that.

**Comment by nickdenardis** [comment]
That is totally possible.

Only downside I see to that approach is still:
- The `$this->has_selected` (making up a var name) would be based on the last ->parse(..) so if there are multiple passes the data is only accurate after each pass.

I'm cool with that as long as you both are.

**Comment by robertvrabel** [comment]
I think its fine. If it comes up that you are using Parse for different menus on one page load, you'd just have to set that selected var as a local var to your app prior to running Parse() again.

Otherwise the only way I could see it working is setting $this->has_selected[$menu_id] = boolean. That way if you parse multiple menus with the same instance of the object it preserves the data you may need.

I think the later though is a bit odd though. I think it would be better if you are parsing multiple menus you could name the instance of the ParseMenu object differently according to the menu and construct a new one each time, so that way the class data is preserved for each menu pass incase it is needed later.

**Comment by nickdenardis** [comment]
Sounds good. 

Let me put something together on your first suggestion and we can see how it feels.

**Comment by nickdenardis** [comment]
Looks like this was solved with https://github.com/waynestate/parse-menu/pull/3
